In [12]:
def is_even(num):
    return True if num % 2 == 0 else False

seq = [10,11,12,13,14,15,16,17,18,19]

def filter_num(is_even, seq):
    out = []
    for i in seq:
        out.append(i) if 
    return out

print(filter_num(is_even,seq))

[10, 12, 14, 16, 18]


# Numpy

In [1]:
import numpy as np

In [6]:
myList = [1,2,3,4,5,6,7,8]
arr = np.array(myList)
print(myList)
type(arr)

[1, 2, 3, 4, 5, 6, 7, 8]


numpy.ndarray

In [11]:
arr.dtype
arr.shape
arr.size
arr.ndim

1

In [19]:
arr = np.array(('a', 'b', 'c', 'd'))
arr
arr.dtype

dtype('<U1')

In [21]:
arr = np.array(('a', 'b', 'c', 'd',10))
arr.dtype

dtype('<U2')

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
arr = np.arange(11,21).reshape(5,2)
arr

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [31]:
arr.ndim

2

In [40]:
arr = np.linspace(11,21,100)
arr

array([11.        , 11.1010101 , 11.2020202 , 11.3030303 , 11.4040404 ,
       11.50505051, 11.60606061, 11.70707071, 11.80808081, 11.90909091,
       12.01010101, 12.11111111, 12.21212121, 12.31313131, 12.41414141,
       12.51515152, 12.61616162, 12.71717172, 12.81818182, 12.91919192,
       13.02020202, 13.12121212, 13.22222222, 13.32323232, 13.42424242,
       13.52525253, 13.62626263, 13.72727273, 13.82828283, 13.92929293,
       14.03030303, 14.13131313, 14.23232323, 14.33333333, 14.43434343,
       14.53535354, 14.63636364, 14.73737374, 14.83838384, 14.93939394,
       15.04040404, 15.14141414, 15.24242424, 15.34343434, 15.44444444,
       15.54545455, 15.64646465, 15.74747475, 15.84848485, 15.94949495,
       16.05050505, 16.15151515, 16.25252525, 16.35353535, 16.45454545,
       16.55555556, 16.65656566, 16.75757576, 16.85858586, 16.95959596,
       17.06060606, 17.16161616, 17.26262626, 17.36363636, 17.46464646,
       17.56565657, 17.66666667, 17.76767677, 17.86868687, 17.96

In [42]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.empty(3*4)

array([9.46307524e-312, 2.47032823e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.33664410e+160, 4.97667917e-091, 2.14620274e+184,
       1.29130344e+160, 1.36312721e+161, 3.99910963e+252, 5.82471487e+257])

In [67]:
np.random.rand(100,100)

array([[0.96645063, 0.14901603, 0.65834221, ..., 0.49755324, 0.1586097 ,
        0.26304986],
       [0.27299905, 0.14339383, 0.69004427, ..., 0.3137518 , 0.6311903 ,
        0.15135953],
       [0.36807212, 0.27251394, 0.18350377, ..., 0.8378622 , 0.61070968,
        0.8967038 ],
       ...,
       [0.07258348, 0.73195591, 0.01073898, ..., 0.01953776, 0.8978567 ,
        0.90388764],
       [0.45409104, 0.22031748, 0.23302549, ..., 0.5858521 , 0.46542485,
        0.70853554],
       [0.06620019, 0.8983449 , 0.11909569, ..., 0.85492209, 0.28996735,
        0.18444268]])

In [68]:
import sys
np.set_printoptions(threshold = sys.maxsize)

In [69]:
np.random.rand(100,100)

array([[9.65509831e-01, 6.93641054e-01, 8.81486845e-02, 6.76224704e-01,
        6.57386971e-01, 4.64911811e-01, 3.39340178e-01, 1.51382227e-02,
        5.11804128e-01, 4.21521470e-01, 3.78107119e-01, 5.40043993e-01,
        5.00805248e-02, 8.90932951e-02, 2.75822812e-01, 7.20518027e-01,
        1.09400201e-01, 4.53061597e-01, 8.68989413e-01, 1.53179721e-01,
        8.02441679e-01, 3.55635377e-02, 2.66719127e-01, 4.33049145e-01,
        9.98206802e-01, 8.99888373e-01, 7.68415434e-01, 3.99656966e-01,
        4.50528751e-01, 2.68481319e-02, 7.24618393e-01, 7.13458612e-01,
        2.52944923e-01, 9.51027003e-01, 2.88706054e-01, 8.34604705e-01,
        9.55460922e-01, 3.15928115e-01, 9.81206078e-01, 8.25629897e-01,
        4.58417656e-01, 2.18191088e-01, 1.32278354e-01, 8.00740007e-01,
        3.09765332e-01, 9.59824900e-02, 6.51699332e-01, 1.30131651e-01,
        3.90556941e-01, 4.43129472e-02, 4.47821680e-01, 6.51008435e-01,
        4.59232756e-02, 5.03585749e-01, 6.42529867e-01, 7.352415

In [71]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
np.arange(100).reshape(25,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [87]:
np.arange(100).reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [95]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
np.arange(100).reshape(10,10).T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [98]:
arr = np.arange(100)
np.reshape(arr, (5,-1), 'C')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [99]:
np.reshape(arr, (5,-1), 'F')

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77,
        82, 87, 92, 97],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78,
        83, 88, 93, 98],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79,
        84, 89, 94, 99]])

In [100]:
arr = np.array([10,20,30])

In [101]:
arr+2

array([12, 22, 32])

In [102]:
arr*2

array([20, 40, 60])

In [103]:
arr-2

array([ 8, 18, 28])

In [104]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558])

In [105]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738])

In [107]:
np.sin(arr * np.pi/180)

array([0.17364818, 0.34202014, 0.5       ])

In [113]:
arr1 = np.array([[1,2],
        [3,4]])
arr2 = np.array([[10,20],
       [30,40]])

print(arr1)
print(arr2)

arr1.ndim
arr2.ndim

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


2

In [115]:
np.dot(arr1, arr2)

array([[ 70, 100],
       [150, 220]])

In [116]:
arr1.dot(arr2)

array([[ 70, 100],
       [150, 220]])

In [117]:
np.sum(arr1)

10

In [119]:
np.min(arr1)

1

In [120]:
np.max(arr1)

4

In [121]:
print(arr1.min())
print(arr1.max())
print(arr1.sum())

1
4
10


In [123]:
arr1

array([[1, 2],
       [3, 4]])

In [124]:
np.sum(arr1, axis = 1)

array([3, 7])

In [126]:
np.sum(arr1, axis = 0)

array([4, 6])

In [127]:
np.add(arr1,arr2)

array([[11, 22],
       [33, 44]])

In [143]:
print(arr1)
print('\n')
print(arr2)
print('\n')
print(arr1|arr2)
print('\n')
print(arr1&arr2)

[[1 2]
 [3 4]]


[[10 20]
 [30 40]]


[[11 22]
 [31 44]]


[[0 0]
 [2 0]]


In [150]:
np.binary_repr(20)

'10100'

In [151]:
arr1.mean()

2.5

In [153]:
np.median(arr1)

2.5

In [155]:
np.std(arr1)

1.118033988749895

In [156]:
np.var(arr1)

1.25